#!/bin/env ruby

require './trollop'
require 'rubygems'

foreman_version = ">= 0"

gem 'foreman', foreman_version
foreman = Gem.bin_path('foreman', 'foreman', foreman_version)

rev = `git rev-parse HEAD 2>/dev/null`

rev_parse = (rev[0..5] if $?.exitstatus == 0) || "UNKNOWN"
version = "#{$0} (0.#{rev_parse})"
opts = Trollop::options do
    @version = version 
    banner <<-EOS
#{@version}
Use this script for generating upstart scripts.  

This script will generate the correct .env for foreman and then invoke
the upstart generation.
EOS
    opt :relay_bin, "Relay binary.", :type => :string, :default => "/opt/stargate/bin/sg-relay"
    opt :server_jar, "Server jar.", :type => :string, :default => "/opt/stargate/libs/rtsp-proxy_0.1.0.jar"
    opt :log_dir, "The log directory for processes.", :default => "/opt/stargate/logs"
    opt :init_dir, "The init dir to install files to.", :default => "init_scripts"
    opt :run_as, "The user that the processes should run as.", :default => "nobody"
    opt :app_name, "The user that the processes should run as.", :default => "MediaGateway"
end
Trollop::die :init_dir, "Must be a valid path." if !opts[:init_dir] || opts[:init_dir].length == 0

File.open  ".env", "w" do |file| 
    file.puts("\# Generated by: #{version}")
    file.puts("relay_bin=\"#{opts[:relay_bin]}\"")
    file.puts("server_jar=\"#{opts[:server_jar]}\"")
end

`mkdir -p #{opts[:init_dir]}`
`#{foreman} export -l #{opts[:log_dir]} -u #{opts[:run_as]} -a #{opts[:app_name]} upstart #{opts[:init_dir]}`

(puts "Succesfully generated files!" if $?.exitstatus == 0) || (puts "Failed to genrate files ;_;")
