require './trollop'
require 'rubygems'

cur_dir = `pwd`.chomp + "/output"
foreman_version = ">= 0"
cur_user = `whoami`.chomp

gem 'foreman', foreman_version
foreman = Gem.bin_path('foreman', 'foreman', foreman_version)

rev = `git rev-parse HEAD 2>/dev/null`

rev_parse = (rev[0..5] if $?.exitstatus == 0) || "UNKNOWN"
version = "#{$0} (0.#{rev_parse})"
opts = Trollop::options do
    @version = version 
    banner <<-EOS
#{@version}
Use this script for generating upstart scripts.  

This script will generate the correct .env for foreman and then invoke
the upstart generation.
EOS
    opt :relay_bin, "Relay binary.", :type => :string, :default => "/opt/stargate/bin/sg-relay"
    opt :server_jar, "Server jar.", :type => :string, :default => "/opt/stargate/libs/rtsp-proxy_0.1.0.jar"
    opt :log_dir, "The log directory for processes.", :default => "#{cur_dir}/logs"
    opt :init_dir, "The init dir to install files to.", :default => "#{cur_dir}/init_scripts"
    opt :run_dir, "The run directory (where the pid is output to).", :default => "#{cur_dir}/run"
    opt :run_as, "The user that the processes should run as.", :default => "#{cur_user}"
    opt :app_name, "The user that the processes should run as.", :default => "MediaGateway"
end
Trollop::die :init_dir, "Must be a valid path." if !opts[:init_dir] || opts[:init_dir].length == 0

File.open  ".env", "w" do |file| 
    file.puts("\# Generated by: #{version}")
    # These must be uppercase due to the way the upstart generator works.
    file.puts("RELAY_BIN=\"#{opts[:relay_bin]}\"")
    file.puts("SERVER_JAR=\"#{opts[:server_jar]}\"")
end

`mkdir -p #{opts[:init_dir]}`
`mkdir -p #{opts[:log_dir]}`
`mkdir -p #{opts[:run_dir]}`
run_foreman = "#{foreman} export -l #{opts[:log_dir]} -u #{opts[:run_as]} -a #{opts[:app_name]} -r #{opts[:run_dir]} upstart #{opts[:init_dir]}"
puts "Running foreman: " + run_foreman
puts `#{run_foreman}`

puts "Succesfully generated files!" if $?.exitstatus == 0 
puts "Failed to genrate files ;_;" unless $?.exitstatus == 0

